[SC-911] Migrate to new hardhat-ethers
1inch/evm-helpers pull request #21
Opened 2023-11-22 10:25 UTC by zZoMROT

2023-11-28 17:35 UTC, byshape approved these changes

2023-12-06 10:17 UTC, ZumZoom requested changes

2023-12-06 10:17 UTC, ZumZoom commented on .github/workflows/ci.yml
> +          node-version: 18.16
```suggestion
          node-version: 20
```

2023-12-06 10:17 UTC, ZumZoom commented on .github/workflows/ci.yml
> +          node-version: 18.16
```suggestion
          node-version: 20
```

2023-12-06 10:17 UTC, ZumZoom commented on .github/workflows/ci.yml
> +          node-version: 18.16
```suggestion
          node-version: 20
```

2023-12-06 10:32 UTC, ZumZoom approved these changes

2023-12-06 10:33 UTC, merged